# Generated by Django 2.1.7 on 2019-11-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memodies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
