# Generated by Django 2.1.7 on 2019-11-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memodies', '0002_auto_20191102_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(null=True),
        ),
    ]
