# Generated by Django 2.1.7 on 2019-11-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memodies', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
