# Generated by Django 2.1.7 on 2019-11-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memodies', '0009_auto_20191112_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
