# Generated by Django 2.1.7 on 2019-11-13 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memodies', '0010_auto_20191112_1552'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('owner', 'track')},
        ),
    ]
