# Generated by Django 2.1.7 on 2019-11-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memodies', '0011_auto_20191113_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memodies.Post'),
        ),
    ]
